### ISSUE TITLE
Track lock files

### ISSUE THREAD

**Issue by kasparsd** [xwp/wp-foo-bar#53] opened 2020-02-10 20:06 UTC
## Feature description

Reliable and reproducible setups help ship stable and reliable code. Tracking lock files for npm and Composer is considered a best practice and we should encourage this behaviour as projects get created from this plugin template.

Renovate is already managing dependency updates in `package.json` and `composer.json` so it shouldn't add any overhead in that regard, too.

**Comment by derekherman** [comment] 2020-02-11 04:29
@kasparsd The issue as I understand it is that the Composer `phpunit` is installed based on the PHP running on the server and the lock file would not allow a different version.

**Comment by derekherman** [comment] 2020-02-28 11:30
It would be fine for locking `npm` but the issue is with Composer. Thoughts?

**Comment by rheinardkorf** [comment] 2020-03-10 22:50
@derekherman can we add platform config to fix this issue?  

See this writeup on similar issues: https://andy-carter.com/blog/composer-php-platform

**Comment by derekherman** [comment] 2020-04-28 08:03
@kasparsd I've added a `package-lock.json`.

@rheinardkorf I am familiar with the platform option in the composer file. However, it doesn't solve the issue from my perspective. Various versions of PHPUnit are compatible with different versions of PHP, when you set the platform like suggested then composer assumes all requests from the cli are coming from the version of PHP in that setting. Let's say for example I want to run the tests in both PHP 7 and 5.6. These two versions require different dependencies. Now if I set the platform to `5.6.20`, the minimum WP requirement then it will always install PHPUnit ^5.7 with PHPCov ^3.1 instead of ^7 & ^6.0 for systems that can use the updated versions. Unless I'm making false assumptions I don't see how the platform option solves the issue.

**Comment by kasparsd** [comment] 2020-04-28 08:29
@derekherman I think we're trying to solve for two concerns here:

- Code compatibility with a range of PHP versions.
- Ability to test the actual functionality of the code using unit tests.

Could we solve both without mixing them?

Writing unit tests that work in a range of PHP versions is probably easy but keeping up with the PHPunit changes between PHPunit versions sounds like a very limiting constrain. Some features of PHPunit from the older versions is not even available in newer versions of PHPunit. The same applies to stuff in the newer versions of PHPunit. Same with different PHPunit helper libraries that typically no longer work with older versions of PHP.

There are three potential solutions to this:

1. Have separate suites of unit tests for each range of PHP and PHPunit versions. This allows us to test specific functionality in specific versions of PHP. This requires the developer to make a choice which isn't ideal. For this to work we introduce a dedicated install step before the CI run to install the required version of PHPunit and update the test task to run a specific suite of tests.

2. Use the same test suite with different versions of PHP and PHPunit by using only the features available in ALL versions of PHPunit. This sounds like the most limiting option in terms of developer experience. The CI setup would again have a dedicated install step to install the correct version of PHPunit.

3. Write tests only for the latest versions of PHP using the latest features available in PHPunit and assume that the PHP compatibility linter takes care of detecting any PHP version related issues.

I personally prefer the third version because it enables larger test coverage with less developer effort because we're able to use the latest features of phpunit and any helper libraries and focus on writing the tests instead of trying to fit both the PHP and PHPunit constraints.

Since the PHP code of the actual functionality would be compatible with all supported versions of PHP, I can't think of any cases where the unit tests would return different results if they had been run on older version of PHPunit.

Therefore, I suggest we use the latest available version of PHPunit and limit the test runner to a CI task that runs with the latest versions of PHP.

**Comment by derekherman** [comment] 2020-04-28 08:45
@kasparsd WordPress unit tests don't work with all version of PHPUnit. Currently if you are running PHP 5.6 you will be using PHPunit 5.7.27 and everything else PHPUnit 7.5.20. So you can't even use the latest and greatest version of PHPUnit which IMO disqualifies option 3.

**Comment by kasparsd** [comment] 2020-04-28 08:54
@derekherman On projects with WP core unit test helpers as a dependency and option no. 3 we would stick with PHPUnit 7 for all unit tests and not run any unit tests on PHP 5.6.

**Comment by derekherman** [comment] 2020-04-28 10:03
I would then ask you what is the point of testing PHP 5.6 if not to run the unit tests?

**Comment by kasparsd** [comment] 2020-04-28 10:38
We would be using [a linter](https://github.com/PHPCompatibility/PHPCompatibility) to check for PHP 5.6+ language features and compatibility while the actual code functionality is tested with PHPUnit at the "default" or suggested version of PHP. 

I can't think of a setup where the same PHP code would return different results depending on a version of PHP so I'm suggesting we run the unit test only once with the "default" version of PHP and use a code linter to ensure the syntax requirements for PHP 5.6+.

**Comment by derekherman** [comment] 2020-05-12 01:54
Fixed by https://github.com/xwp/wp-foo-bar/commit/ab2a5c99c769ab37ed061362de7b5d56857beb56

**Closed as completed by derekherman** 2020-05-12 01:54 UTC
